import { SectionType, NavigationItem } from '../types';
import {
    SectionBorder,
    SectionBreakpoints,
    SectionColor,
    SectionDisplay,
    SectionFlexBox,
    SectionFloat,
    SectionFontWeight,
    SectionGrid,
    SectionHeight,
    SectionMaxWidth,
    SectionOpacity,
    SectionPosition,
    SectionRadius,
    SectionShadow,
    SectionSpacing,
    SectionTextAlign,
    SectionTextDecoration,
    SectionTextTransform,
    SectionTypography,
    SectionWidth,
} from '../pages/sections';

const navigation: Record<SectionType, NavigationItem> = {
    [SectionType.BORDER]: { displayName: 'Border', page: SectionBorder },
    [SectionType.BREAKPOINTS]: { displayName: 'Breakpoints', page: SectionBreakpoints },
    [SectionType.COLOR]: { displayName: 'Color', page: SectionColor },
    [SectionType.DISPLAY]: { displayName: 'Display', page: SectionDisplay },
    [SectionType.FLEXBOX]: { displayName: 'Flex Box', page: SectionFlexBox },
    [SectionType.FLOAT]: { displayName: 'Float', page: SectionFloat },
    [SectionType.FONT_WEIGHT]: { displayName: 'Font Weight', page: SectionFontWeight },
    [SectionType.GRID]: { displayName: 'Grid', page: SectionGrid },
    [SectionType.HEIGHT]: { displayName: 'Height', page: SectionHeight },
    [SectionType.MAX_WIDTH]: { displayName: 'Max Width', page: SectionMaxWidth },
    [SectionType.OPACITY]: { displayName: 'Opacity', page: SectionOpacity },
    [SectionType.POSITION]: { displayName: 'Position', page: SectionPosition },
    [SectionType.RADIUS]: { displayName: 'Radius', page: SectionRadius },
    [SectionType.SHADOW]: { displayName: 'Shadow', page: SectionShadow },
    [SectionType.SPACING]: { displayName: 'Spacing', page: SectionSpacing },
    [SectionType.TEXT_ALIGN]: { displayName: 'Text Align', page: SectionTextAlign },
    [SectionType.TEXT_DECORATION]: { displayName: 'Text Decoration', page: SectionTextDecoration },
    [SectionType.TEXT_TRANSFORM]: { displayName: 'Text Transform', page: SectionTextTransform },
    [SectionType.TYPOGRAPHY]: { displayName: 'Typography', page: SectionTypography },
    [SectionType.WIDTH]: { displayName: 'Width', page: SectionWidth },
};

export default navigation;
